- .editorconfig
- build.gradle
- src/main/groovy/to/wetransform/halecli/CLI.java
- src/main/groovy/to/wetransform/halecli/VersionCommand.groovy
- src/main/groovy/to/wetransform/halecli/groovy/GroovyShellCommand.groovy
- src/main/groovy/to/wetransform/halecli/internal/CustomMetaClassCreationHandle.java
- src/main/groovy/to/wetransform/halecli/internal/Init.java
- src/main/groovy/to/wetransform/halecli/project/AbstractDeriveProjectCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/advisor/SaveAlignmentAdvisor.java
- src/main/groovy/to/wetransform/halecli/project/advisor/SaveProjectAdvisor.java
- src/main/groovy/to/wetransform/halecli/project/alignment/FilterAlignmentCommand.groovy
Also added eclipseconfig plugin to the project.
> first version of base alignment filtering support

- build.gradle
- src/main/groovy/to/wetransform/halecli/project/migrate/AbstractMigrateCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/migrate/DefaultSchemaMigration.groovy
- src/main/groovy/to/wetransform/halecli/project/migrate/MatchingMigration.groovy
- src/main/groovy/to/wetransform/halecli/project/migrate/MigrateMatchingCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/migrate/ProjectMigrator.java
- src/main/groovy/to/wetransform/halecli/project/migrate/ReplaceSourceCommand.groovy
- src/main/groovy/to/wetransform/halecli/util/ProjectCLI.groovy
- src/main/groovy/to/wetransform/halecli/util/SchemaCLI.groovy
- src/main/resources/plugin.xml
Functionality that might at least partly be later moved to hale in context of https://github.com/halestudio/hale/issues/182
> first version of commands for migrating projects to other schemas

- build.gradle
With these dependencies Schematron validation also works in hale-cli.
> Add dependencies for Schematron validation

- CHANGELOG.md
- build.gradle
> prepare 3.3.0 release

- src/main/groovy/to/wetransform/halecli/data/RewriteCommand.groovy
- src/main/groovy/to/wetransform/halecli/util/HaleIOHelper.java
- src/main/groovy/to/wetransform/halecli/util/InstanceCLI.groovy
- src/main/groovy/to/wetransform/halecli/util/SchemaCLI.groovy
- src/main/resources/plugin.xml
- src/test/groovy/to/wetransform/halecli/data/RewriteCommandTest.groovy
> add generic command for rewriting a source

- src/main/groovy/to/wetransform/halecli/util/InstanceCLI.groovy
- src/test/groovy/to/wetransform/halecli/data/RewriteCommandTest.groovy
Also adapt to changed StoreInstancesJob constructor.
Requires https://github.com/halestudio/hale/pull/403 to be merged.
> add test for non-passthrough writer in rewrite

- CHANGELOG.md
- build.gradle
- src/main/groovy/to/wetransform/halecli/data/RewriteCommand.groovy
- src/main/groovy/to/wetransform/halecli/data/SplitCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/alignment/FilterAlignmentCommand.groovy
- src/main/groovy/to/wetransform/halecli/util/HaleIOHelper.java
- src/main/groovy/to/wetransform/halecli/util/InstanceCLI.groovy
- src/main/groovy/to/wetransform/halecli/util/SchemaCLI.groovy
- src/main/resources/plugin.xml
- src/test/groovy/to/wetransform/halecli/data/RewriteCommandTest.groovy
- src/test/resources/testdata/inspire.gml
> Prepare 3.3.1 release

- build.gradle
- src/main/groovy/to/wetransform/halecli/schema/RewriteCommand.groovy
- src/main/groovy/to/wetransform/halecli/util/SchemaCLI.groovy
- src/main/resources/plugin.xml
e.g. for creating a hale schema definition
> add rewrite command for schemas

- src/main/groovy/to/wetransform/halecli/data/RewriteCommand.groovy
- src/main/groovy/to/wetransform/halecli/data/SplitCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/ProjectHelper.groovy
- src/main/groovy/to/wetransform/halecli/project/migrate/AbstractMigratorCommand.groovy
- src/main/groovy/to/wetransform/halecli/schema/RewriteCommand.groovy
- src/main/groovy/to/wetransform/halecli/util/InstanceCLI.groovy
- src/main/groovy/to/wetransform/halecli/util/ProjectCLI.groovy
- src/main/groovy/to/wetransform/halecli/util/SchemaCLI.groovy
Depends on https://github.com/halestudio/hale/pull/540 being merged.
> handle reports in a uniform way

- CHANGELOG.md
- build.gradle
hale-cli release based on hale 3.3.2 w/o alignment merger
> Prepare 3.3.2 release

- build.gradle
- src/main/groovy/to/wetransform/halecli/project/AbstractDeriveProjectCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/ExportProjectCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/ProjectHelper.groovy
- src/main/groovy/to/wetransform/halecli/project/advisor/SaveAlignmentAdvisor.java
- src/main/groovy/to/wetransform/halecli/project/advisor/SaveProjectAdvisor.java
- src/main/groovy/to/wetransform/halecli/project/match/MatchSchemasCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/migrate/AbstractMigratorCommand.groovy
- src/main/groovy/to/wetransform/halecli/util/HaleConnectCLI.groovy
- src/main/groovy/to/wetransform/halecli/util/ProjectCLI.groovy
- src/main/resources/plugin.xml
Also supports saving projects to hale connect
> add command for exporting projects

- src/main/groovy/to/wetransform/halecli/project/ProjectHelper.groovy
- src/main/groovy/to/wetransform/halecli/util/ProjectCLI.groovy
Commands that save or export hale projects now support arguments that allow passing on settings for
the project writer.
> feat: support specifying settings for project writers

- CHANGELOG.md
- build.gradle
- src/main/groovy/to/wetransform/halecli/project/AbstractDeriveProjectCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/ExportProjectCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/ProjectHelper.groovy
- src/main/groovy/to/wetransform/halecli/project/advisor/SaveAlignmentAdvisor.java
- src/main/groovy/to/wetransform/halecli/project/advisor/SaveProjectAdvisor.java
- src/main/groovy/to/wetransform/halecli/project/match/MatchSchemasCommand.groovy
- src/main/groovy/to/wetransform/halecli/project/migrate/AbstractMigratorCommand.groovy
- src/main/groovy/to/wetransform/halecli/util/HaleConnectCLI.groovy
- src/main/groovy/to/wetransform/halecli/util/ProjectCLI.groovy
- src/main/resources/logback.xml
- src/main/resources/plugin.xml
> hale-cli 3.5.0

- CHANGELOG.md
- build.gradle
Sorry for the mess, instead of merging PR #62 I rebased it, so `devel` now gets all the rebased commits from `master`.
> build: new development version

- src/main/groovy/to/wetransform/halecli/util/InstanceCLI.groovy
- src/test/groovy/to/wetransform/halecli/data/RewriteCommandTest.groovy
- src/test/resources/testdata/inspire2.gml
This reuses the functionality found in the command for the
transformation.
SVC-516
> feat: support specifying filters when loading instance data

- build.gradle
Use latest hale studio snapshot builds.
ING-2671
> build: new development snapshot

- README.md
- build.gradle
> build: migrate to java 17

- CHANGELOG.md
- build.gradle
Update changelog.md taken from the release 5.1.0 and 
set up the devel branch version to a snapshot.
ING-4011
> build: Update software to the next snapshot version

- .github/workflows/check.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
> Update gradle workflows and make sure to build release artifacts after version was set

- build.gradle
See also https://github.com/ngageoint/geopackage-java/issues/62
> fix: fix conflicting SLF4J providers introduced by dependencies
